using System.Collections.Generic;

namespace RThomaz.Application.Financeiro.Helpers.JsTree
{
    public class JsTreeNode
    {
        public JsTreeNode()
        {
            state = new State();
            children = new List<JsTreeNode>();
            li_attr = new JsTreeLiAttribute();
            a_attr = new JsTreeAAttribute();
        }

        // will be autogenerated if omitted
        public string id { get; set; }

        // node text
        public string text { get; set; }

        // string for custom
        public string icon { get; set; }

        public State state { get; set; }

        // array of strings or objects
        public List<JsTreeNode> children { get; set; }

        // attributes for the generated LI node
        public JsTreeLiAttribute li_attr { get; set; }

        // attributes for the generated A node
        public JsTreeAAttribute a_attr { get; set; }       
    }    
}